# Generated by Django 3.1.1 on 2021-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211209_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
