# Generated by Django 3.1.1 on 2021-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20211213_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateTimeField(verbose_name='%B %d, %Y %I:%M'),
        ),
    ]
