# Generated by Django 3.1.1 on 2021-12-13 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211213_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 17, 21, 18, 168984)),
        ),
    ]
